### ISSUE TITLE
Amplitude analytics-browser 2.11.0 with autocapture: true freezes on click on dropdown menu

### ISSUE THREAD

**Issue by mjsilva** [amplitude/Amplitude-Node#196] opened 2024-08-27 03:28 UTC
## Expected Behavior
Not freeze and capture the interaction

## Current Behavior
We recently upgraded from:
```
    "@amplitude/analytics-browser": "^2.9.3",
    "@amplitude/plugin-session-replay-browser": "^1.6.5",
```
to
```
    "@amplitude/analytics-browser": "^2.11.0",
    "@amplitude/plugin-session-replay-browser": "^1.6.21",
```

and enabled `autocapture`. But it broken one of our dropdown menu select and had to revert back to previous version. Essentially when a user clicked on a dropdown menu it would just freeze any interaction like JS thread was in an infinite loop. Does anyone else had this problem?

## Possible Solution
downgrade to ^2.9.3

## Steps to Reproduce
I haven't tried to reproduce it on a clean repo with just amplitude enabled as that's a lot of work. Just trying to understand if anyone else is having this issue. Can do further digging if needed.

## Environment
- SDK Version: mentioned above
- Node version: v20.13.1

**Comment by izaaz** [comment] 2024-08-27 17:23
@mjsilva - I see that the issue is marked closed. Were you able to resolve the issue? This shouldn't be happening so checking in to see if there's an issue with the SDK.

**Comment by lewgordon-amplitude** [comment] 2024-08-27 17:25
I think this is the new issue? https://github.com/amplitude/Amplitude-TypeScript/issues/861

**Comment by izaaz** [comment] 2024-08-27 17:50
ah! Thanks @lewgordon-amplitude. I'll close this and we can track this on the typescript repo.

**Closed as completed by izaaz** 2024-08-27 17:50 UTC
Labels: bug
