### ISSUE TITLE
Not including OS in Node library payload overrides user properties from client library payload with empty string

### ISSUE THREAD

**Issue by JayAtCricket** [amplitude/Amplitude-Node#72] opened 2021-01-13 08:22 UTC
## Expected Behavior
If a user has an OS user property set from an event logged via the client-side library, then a subsequent event from the node library that omits user attributes in the payload should not override attributes with empty strings, namely the os_name attribute.

## Current Behavior
Starting with a client event we get:

![image](https://user-images.githubusercontent.com/77381174/104425117-1e01e380-5535-11eb-8d6b-cefcd852acf2.png)

and after sending the node event we get an empty string that overrides the User's OS attribute:

![image](https://user-images.githubusercontent.com/77381174/104425235-45f14700-5535-11eb-960e-13baa6b78586.png)

## Possible Solution
Somewhere in the API2 service the absence of an `os_name` in the payload is being interpreted as an empty string and that should be resolved.

## Steps to Reproduce
Please see [here](https://github.com/JayAtCricket/AmplitudeNodeMissingOSBug) for a simple React application demonstrating this bug. 
1. Update the `src/App.js` file with an appropriate Amplitude Project API key
2. Start the dev server with `yarn start`
2. Visit the app
3. Click the log event with client-side SDK button to see an event show up in the project with the user's OS information appropriately shown in the user properties in the event as well as of the User itself
4. Click the log event with node SDK button to see an event show up in the project with an empty string for the OS and see that it also overrides the User's overall OS to an empty string.

## Environment
- SDK Version: Latest
- Node version: Latest

**Comment by kelvin-lu** [comment] 2021-01-21 08:27
Hey @JayAtCricket !

First off, thanks so much for creating an application and creating an example - this will be super helpful for our data team. I'll go ahead and continue this investigation with our internal team to see if the possible soln you provided matches up with the root cause and follow up here. Let us know if you find other issues with event ingestion!

**Comment by tommedema** [comment] 2021-02-10 22:36
For us the OS is set to an empty string even when specifying os_name

**Comment by ajhorst** [comment] 2021-03-23 20:40
fixed with v1.5.2, which is now available

**Closed by ajhorst** 2021-03-23 20:40 UTC
Labels: bug
